@startuml TEST
'left to right direction
skinparam linetype polyline
hide circle
!includeurl https://raw.githubusercontent.com/matthewjosephtaylor/plantuml-style/master/style.pu

' Class Definitions
class Produkt {
  Name
  gesperrt
}

class Produktmenge << singleton >> {
}
note top of Produktmenge : Klasse als Singleton implementieren
class Anleitung {
    Abweisungsgrund
}
class Benutzer as "Benutzer \n{abstract}" {
   benutername
   e-mail
   klarname
   kennwort

   login()
}
class Rolle {
}
class Fachprüfer {
    anleitungFreigeben()
    anleitungSperren()
}
class Sprachprüfer {
    übersetzungFreigeben()
    freizugebendeAnleitungenAnzeigen()
    übersetzungSperren()
}
class Übsersetzer {
    übersetzungHochladen()
    vorhandeneÜbersetzungenAnzeigen()
    fehlendeÜbersetzungenAnzeigen()
    abgelehnteÜbersetzungenAnzeigen()
}
class Admin {
    benutzerPflegen()
    benutzerAnlegen()
    sprachLandKombinationPflegen()
    länderSprachenÜbersetzernZuordnen()
    produktLöschen()
    übersetzungLöschen()
    berichtAnfordern()
}
class Produktmanager {
    produktErstellen()
    produktBearbeiten()
    produktSperren()
    produktFreigeben()
}
class Land {
    Kurzform
}
class Sprache {
    Kurzform
}
class Kombination {
}
class Mehrproduktuser {
}
class Bericht {
   Aktivitäten
}
class Status << enumeration >> {
   offen
   zurückgewiesen
   fachlich geprüft
   sprachlich geprüft
   final
}

'Vererbung
Rolle <|-- Fachprüfer
Rolle <|-- Mehrproduktuser


Mehrproduktuser <|-- Sprachprüfer
Mehrproduktuser <|-- Übsersetzer
Mehrproduktuser <|-- Admin
Mehrproduktuser <|-- Produktmanager
'Assoziationen
Benutzer "0..*" -right- "1..*" Rolle : besitzt >

Kombination "0..*  " -- "1" Admin : < pflegt
Kombination "0..*  " -- "0..*" Übersetzer
Kombination "1" -- "0..1\t" Anleitung

Land "1" -- "0..*\n" Kombination 
Sprache "1" -- "0..*  " Kombination

Anleitung "1" -- "1" Status

Produktmenge "1" -- "0..*  " Produkt 
Produktmenge "0..1   " -- "1..*  " Mehrproduktuser 

Produkt "1" -- " 0..*\r\n" Anleitung 
Produkt "0..1  " -- "1..*" Fachprüfer
Produkt "0..1" -- "1..*  " Land

Sprache "0..*" -- "0..1" Sprachprüfer

' Assoziationsklasse
Bericht .. (Produkt, Fachprüfer)
(Mehrproduktuser, Produktmenge) .. Bericht
@enduml
