@startuml Klassendiagramm
'left to right direction
skinparam linetype polyline
hide circle
!includeurl https://raw.githubusercontent.com/matthewjosephtaylor/plantuml-style/master/style.pu

' Class Definitions
class Produkt {
  Name
  gesperrt
}

class Produktmenge << singleton >> {
}
note top of Produktmenge : Klasse als Singleton implementieren
class Anleitung
class Benutzer {
   benutername
   e-mail
   klarname
   kennwort

   login()
}
class Rolle as "Rolle \n{abstract}"{
}
class Fachprüfer {
    anleitungFreigeben()
    anleitungZurückweisen()
}
class Sprachprüfer {
    anleitungFreigeben()
    freizugebendeAnleitungenAnzeigen()
    anleitungZurückweisen()
}
class Übersetzer {
    anleitungHochladen()
    vorhandeneAnleitungenAnzeigen()
    fehlendeAnleitungenAnzeigen()
    abgelehnteAnleitungenAnzeigen()
}
class Admin {
    benutzerPflegen()
    benutzerAnlegen()
    sprachLandKombinationPflegen()
    länderSprachenÜbersetzernZuordnen()
    produktLöschen()
    anleitungLöschen()
    berichtAnfordern()
}
class Produktmanager {
    produktErstellen()
    produktBearbeiten()
    produktSperren()
    produktFreigeben()
    fehlendeAnleitungenAnschauen()
    freigabestatusAnschauen()
}
class Land {
    Kurzform
}
class Sprache {
    Kurzform
}
class Kombination {
}
class Mehrproduktuser as "Mehrproduktuser \n{abstract}" {
}
class Bericht {
   Aktivitäten
}
class Status << enumeration >> {
   offen
   zurückgewiesen
   sprachlich geprüft
   fachlich geprüft
   final
}
class Abweisungsgrund {
    Grund
    Type
}
'Vererbung
Rolle <|-- Fachprüfer
Rolle <|-- Mehrproduktuser


Mehrproduktuser <|-- Sprachprüfer
Mehrproduktuser <|-- Übersetzer
Produktmanager -up-|> Mehrproduktuser
Mehrproduktuser <|-- Admin

'Assoziationen
Benutzer "0..*" -right- "1..*" Rolle : besitzt >

Produktmanager -[hidden]- Admin

Kombination "0..*   " -left- "1" Admin : < pflegt
Kombination "0..*  " -- "0..*" Übersetzer
Kombination "1" -- "0..1\t" Anleitung

Land "1  " -left- "  0..*" Kombination 
Sprache "1" -- "0..*  " Kombination

Anleitung "1  " -- "1" Status
Anleitung "1" -- "0..2  " Abweisungsgrund

Produktmenge "1" -- "0..*     " Produkt 
Produktmenge "   0..1    " -- "1..*" Mehrproduktuser 

Produkt "\n1   " -- " 0..*" Anleitung 
Fachprüfer "0..*" -- "0..1" Produkt
Produkt "  0..*" ---- "1..* " Land

Sprache "0..*  " -- "0..*" Sprachprüfer

' Assoziationsklasse
Bericht .. (Produkt, Fachprüfer)
(Mehrproduktuser, Produktmenge) .. Bericht
@enduml
